[versions]
junit5 = "5.10.2"
snakeYamlEngine = "2.10"
typesafeConfig = "1.4.3"
jetbrainsAnnotations = "26.0.2"

[libraries]
snakeYamlEngine = { module = "org.snakeyaml:snakeyaml-engine", version.ref = "snakeYamlEngine" }
typesafeConfig = { module = "com.typesafe:config", version.ref = "typesafeConfig" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
